name: generate pixel cat pet

on:
  schedule:
    - cron: "23 */6 * * *" # every 6 hours
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  pet:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - uses: actions/checkout@v4
      - uses: prsdx/github-pet@v1
        with:
          username: ionik0
          timezone-offset-minutes: "330"
          pet-name: "Ginger"
          accent-color: "#FF7518"
          attribution: "false"
